export const saProvinces = [
  {
    name: 'Gauteng',
    slug: 'gauteng',
    abbr: 'GP',
    cities: [
      { name: 'Johannesburg', slug: 'johannesburg', alt: ['Joburg', 'Jozi', 'JHB'] },
      { name: 'Sandton', slug: 'sandton' },
      { name: 'Midrand', slug: 'midrand' },
      { name: 'Centurion', slug: 'centurion' },
      { name: 'Pretoria', slug: 'pretoria', alt: ['Tshwane', 'PTA'] },
      { name: 'Randburg', slug: 'randburg' },
      { name: 'Roodepoort', slug: 'roodepoort' },
      { name: 'Germiston', slug: 'germiston' },
      { name: 'Alberton', slug: 'alberton' },
      { name: 'Edenvale', slug: 'edenvale' },
      { name: 'Boksburg', slug: 'boksburg' },
      { name: 'Benoni', slug: 'benoni' },
      { name: 'Brakpan', slug: 'brakpan' },
      { name: 'Springs', slug: 'springs' },
      { name: 'Soweto', slug: 'soweto' },
      { name: 'Krugersdorp', slug: 'krugersdorp' },
      { name: 'Vereeniging', slug: 'vereeniging', alt: ['Vaal'] },
      { name: 'Vanderbijlpark', slug: 'vanderbijlpark' },
      { name: 'Nigel', slug: 'nigel' },
      { name: 'Kempton Park', slug: 'kempton-park' },
      { name: 'Tembisa', slug: 'tembisa' },
      { name: 'Fourways', slug: 'fourways' },
      { name: 'Bryanston', slug: 'bryanston' },
      { name: 'Rosebank', slug: 'rosebank' },
      { name: 'Bedfordview', slug: 'bedfordview' },
      { name: 'Diepsloot', slug: 'diepsloot' },
      { name: 'Soshanguve', slug: 'soshanguve' },
      { name: 'Mamelodi', slug: 'mamelodi' },
      { name: 'Menlyn', slug: 'menlyn' },
      { name: 'Lynnwood', slug: 'lynnwood' },
      { name: 'Hatfield', slug: 'hatfield' },
      { name: 'Rivonia', slug: 'rivonia' },
      { name: 'Woodmead', slug: 'woodmead' },
      { name: 'Sunninghill', slug: 'sunninghill' },
      { name: 'Kyalami', slug: 'kyalami' },
      { name: 'Midrand', slug: 'halfway-house', name: 'Halfway House' },
      { name: 'Parktown', slug: 'parktown' },
      { name: 'Rosebank', slug: 'melrose', name: 'Melrose' },
      { name: 'Hyde Park', slug: 'hyde-park' },
      { name: 'Illovo', slug: 'illovo' },
      { name: 'Norwood', slug: 'norwood' },
      { name: 'Alexandra', slug: 'alexandra' },
      { name: 'Lenasia', slug: 'lenasia' },
      { name: 'Orange Farm', slug: 'orange-farm' },
      { name: 'Atteridgeville', slug: 'atteridgeville' },
      { name: 'Brooklyn', slug: 'brooklyn-pretoria', name: 'Brooklyn Pretoria' },
      { name: 'Waterkloof', slug: 'waterkloof' },
      { name: 'Lyttelton', slug: 'lyttelton' },
      { name: 'Irene', slug: 'irene' },
      { name: 'Randfontein', slug: 'randfontein' },
      { name: 'Ekurhuleni', slug: 'ekurhuleni' },
    ]
  },
  {
    name: 'Western Cape',
    slug: 'western-cape',
    abbr: 'WC',
    cities: [
      { name: 'Cape Town', slug: 'cape-town', alt: ['Capetown', 'CT'] },
      { name: 'Bellville', slug: 'bellville' },
      { name: 'Paarl', slug: 'paarl' },
      { name: 'Stellenbosch', slug: 'stellenbosch' },
      { name: 'Somerset West', slug: 'somerset-west' },
      { name: 'George', slug: 'george' },
      { name: 'Knysna', slug: 'knysna' },
      { name: 'Mossel Bay', slug: 'mossel-bay' },
      { name: 'Oudtshoorn', slug: 'oudtshoorn' },
      { name: 'Worcester', slug: 'worcester' },
      { name: 'Hermanus', slug: 'hermanus' },
      { name: 'Strand', slug: 'strand' },
      { name: 'Claremont', slug: 'claremont' },
      { name: 'Rondebosch', slug: 'rondebosch' },
      { name: 'Wynberg', slug: 'wynberg' },
      { name: 'Muizenberg', slug: 'muizenberg' },
      { name: 'Fish Hoek', slug: 'fish-hoek' },
      { name: "Simon's Town", slug: 'simons-town' },
      { name: 'Hout Bay', slug: 'hout-bay' },
      { name: 'Green Point', slug: 'green-point' },
      { name: 'Sea Point', slug: 'sea-point' },
      { name: 'Bloubergstrand', slug: 'bloubergstrand' },
      { name: 'Melkbosstrand', slug: 'melkbosstrand' },
      { name: 'Durbanville', slug: 'durbanville' },
      { name: 'Brackenfell', slug: 'brackenfell' },
      { name: 'Century City', slug: 'century-city' },
      { name: 'Milnerton', slug: 'milnerton' },
      { name: 'Plettenberg Bay', slug: 'plettenberg-bay' },
      { name: 'Jeffreys Bay', slug: 'jeffreys-bay' },
      { name: 'Wilderness', slug: 'wilderness' },
      { name: 'Langebaan', slug: 'langebaan' },
      { name: 'Saldanha', slug: 'saldanha' },
      { name: 'Wellington', slug: 'wellington' },
      { name: 'Franschhoek', slug: 'franschhoek' },
      { name: 'Malmesbury', slug: 'malmesbury' },
      { name: 'Swellendam', slug: 'swellendam' },
      { name: 'Caledon', slug: 'caledon' },
      { name: 'Grabouw', slug: 'grabouw' },
      { name: 'Robertson', slug: 'robertson' },
      { name: 'Montagu', slug: 'montagu' },
      { name: 'Barrydale', slug: 'barrydale' },
      { name: 'Beaufort West', slug: 'beaufort-west' },
      { name: 'Parow', slug: 'parow' },
      { name: 'Goodwood', slug: 'goodwood' },
      { name: 'Pinelands', slug: 'pinelands' },
      { name: 'Khayelitsha', slug: 'khayelitsha' },
      { name: 'Mitchells Plain', slug: 'mitchells-plain' },
      { name: 'Athlone', slug: 'athlone' },
      { name: 'Kuils River', slug: 'kuils-river' },
      { name: 'Gordon\'s Bay', slug: 'gordons-bay' },
      { name: 'Tableview', slug: 'tableview' },
      { name: 'Parklands', slug: 'parklands' },
    ]
  },
  {
    name: 'KwaZulu-Natal',
    slug: 'kwazulu-natal',
    abbr: 'KZN',
    cities: [
      { name: 'Durban', slug: 'durban', alt: ['DBN', 'eThekwini'] },
      { name: 'Pietermaritzburg', slug: 'pietermaritzburg', alt: ['PMB'] },
      { name: 'Umhlanga', slug: 'umhlanga' },
      { name: 'Pinetown', slug: 'pinetown' },
      { name: 'Westville', slug: 'westville' },
      { name: 'Hillcrest', slug: 'hillcrest' },
      { name: 'Amanzimtoti', slug: 'amanzimtoti' },
      { name: 'Ballito', slug: 'ballito' },
      { name: 'Port Shepstone', slug: 'port-shepstone' },
      { name: 'Ladysmith', slug: 'ladysmith' },
      { name: 'Newcastle', slug: 'newcastle' },
      { name: 'Richards Bay', slug: 'richards-bay' },
      { name: 'Vryheid', slug: 'vryheid' },
      { name: 'Kokstad', slug: 'kokstad' },
      { name: 'Scottburgh', slug: 'scottburgh' },
      { name: 'Margate', slug: 'margate' },
      { name: 'Tongaat', slug: 'tongaat' },
      { name: 'Phoenix', slug: 'phoenix-kzn', name: 'Phoenix KZN' },
      { name: 'Chatsworth', slug: 'chatsworth' },
      { name: 'Stanger', slug: 'stanger' },
      { name: 'KwaDukuza', slug: 'kwadukuza' },
      { name: 'Mtubatuba', slug: 'mtubatuba' },
      { name: 'Empangeni', slug: 'empangeni' },
      { name: 'Ulundi', slug: 'ulundi' },
      { name: 'Dundee', slug: 'dundee' },
      { name: 'Howick', slug: 'howick' },
      { name: 'Estcourt', slug: 'estcourt' },
      { name: 'Ixopo', slug: 'ixopo' },
      { name: 'Greytown', slug: 'greytown' },
      { name: 'Harrismith', slug: 'harrismith-kzn', name: 'Harrismith' },
      { name: 'Umzinto', slug: 'umzinto' },
      { name: 'Umlazi', slug: 'umlazi' },
      { name: 'Kingsburgh', slug: 'kingsburgh' },
      { name: 'La Lucia', slug: 'la-lucia' },
      { name: 'Kloof', slug: 'kloof' },
    ]
  },
  {
    name: 'Eastern Cape',
    slug: 'eastern-cape',
    abbr: 'EC',
    cities: [
      { name: 'Port Elizabeth', slug: 'port-elizabeth', alt: ['Gqeberha', 'PE'] },
      { name: 'Gqeberha', slug: 'gqeberha' },
      { name: 'East London', slug: 'east-london' },
      { name: 'Grahamstown', slug: 'grahamstown', alt: ['Makhanda'] },
      { name: 'Makhanda', slug: 'makhanda' },
      { name: 'Queenstown', slug: 'queenstown' },
      { name: 'Uitenhage', slug: 'uitenhage' },
      { name: 'Despatch', slug: 'despatch' },
      { name: 'Humansdorp', slug: 'humansdorp' },
      { name: 'Port Alfred', slug: 'port-alfred' },
      { name: 'Aliwal North', slug: 'aliwal-north' },
      { name: 'Cradock', slug: 'cradock' },
      { name: 'Graaff-Reinet', slug: 'graaff-reinet' },
      { name: 'King William\'s Town', slug: 'king-williams-town', alt: ['Bhisho'] },
      { name: 'Bhisho', slug: 'bhisho' },
      { name: 'Butterworth', slug: 'butterworth' },
      { name: 'Mthatha', slug: 'mthatha', alt: ['Umtata'] },
      { name: 'Cofimvaba', slug: 'cofimvaba' },
      { name: 'Komani', slug: 'komani' },
      { name: 'Dimbaza', slug: 'dimbaza' },
      { name: 'Alice', slug: 'alice-eastern-cape', name: 'Alice' },
      { name: 'Bedford', slug: 'bedford-eastern-cape', name: 'Bedford' },
      { name: 'Barkly East', slug: 'barkly-east' },
      { name: 'Elliot', slug: 'elliot' },
      { name: 'Lady Frere', slug: 'lady-frere' },
      { name: 'Sterkstroom', slug: 'sterkstroom' },
      { name: 'Whittlesea', slug: 'whittlesea' },
    ]
  },
  {
    name: 'Free State',
    slug: 'free-state',
    abbr: 'FS',
    cities: [
      { name: 'Bloemfontein', slug: 'bloemfontein', alt: ['Bloem', 'Mangaung'] },
      { name: 'Welkom', slug: 'welkom' },
      { name: 'Bethlehem', slug: 'bethlehem' },
      { name: 'Phuthaditjhaba', slug: 'phuthaditjhaba' },
      { name: 'Sasolburg', slug: 'sasolburg' },
      { name: 'Kroonstad', slug: 'kroonstad' },
      { name: 'Parys', slug: 'parys' },
      { name: 'Virginia', slug: 'virginia-fs', name: 'Virginia' },
      { name: 'Odendaalsrus', slug: 'odendaalsrus' },
      { name: 'Frankfort', slug: 'frankfort' },
      { name: 'Ficksburg', slug: 'ficksburg' },
      { name: 'Ladybrand', slug: 'ladybrand' },
      { name: 'Botshabelo', slug: 'botshabelo' },
      { name: 'Thaba Nchu', slug: 'thaba-nchu' },
      { name: 'Hennenman', slug: 'hennenman' },
      { name: 'Viljoenskroon', slug: 'viljoenskroon' },
      { name: 'Theunissen', slug: 'theunissen' },
      { name: 'Wesselsbron', slug: 'wesselsbron' },
      { name: 'Winburg', slug: 'winburg' },
      { name: 'Vredefort', slug: 'vredefort' },
      { name: 'Steynsrus', slug: 'steynsrus' },
      { name: 'Senekal', slug: 'senekal' },
    ]
  },
  {
    name: 'Limpopo',
    slug: 'limpopo',
    abbr: 'LP',
    cities: [
      { name: 'Polokwane', slug: 'polokwane', alt: ['Pietersburg'] },
      { name: 'Pietersburg', slug: 'pietersburg' },
      { name: 'Tzaneen', slug: 'tzaneen' },
      { name: 'Phalaborwa', slug: 'phalaborwa' },
      { name: 'Thohoyandou', slug: 'thohoyandou' },
      { name: 'Mokopane', slug: 'mokopane' },
      { name: 'Bela-Bela', slug: 'bela-bela', alt: ['Warmbaths'] },
      { name: 'Lephalale', slug: 'lephalale', alt: ['Ellisras'] },
      { name: 'Seshego', slug: 'seshego' },
      { name: 'Makhado', slug: 'makhado', alt: ['Louis Trichardt'] },
      { name: 'Louis Trichardt', slug: 'louis-trichardt' },
      { name: 'Musina', slug: 'musina', alt: ['Messina'] },
      { name: 'Giyani', slug: 'giyani' },
      { name: 'Malamulele', slug: 'malamulele' },
      { name: 'Thabazimbi', slug: 'thabazimbi' },
      { name: 'Northam', slug: 'northam' },
      { name: 'Marble Hall', slug: 'marble-hall' },
      { name: 'Jane Furse', slug: 'jane-furse' },
      { name: 'Burgersfort', slug: 'burgersfort' },
      { name: 'Lebowakgomo', slug: 'lebowakgomo' },
      { name: 'Alldays', slug: 'alldays' },
      { name: 'Hoedspruit', slug: 'hoedspruit' },
      { name: 'Haenertsburg', slug: 'haenertsburg' },
    ]
  },
  {
    name: 'Mpumalanga',
    slug: 'mpumalanga',
    abbr: 'MP',
    cities: [
      { name: 'Nelspruit', slug: 'nelspruit', alt: ['Mbombela'] },
      { name: 'Mbombela', slug: 'mbombela' },
      { name: 'Witbank', slug: 'witbank', alt: ['eMalahleni'] },
      { name: 'eMalahleni', slug: 'emalahleni' },
      { name: 'Secunda', slug: 'secunda' },
      { name: 'Standerton', slug: 'standerton' },
      { name: 'Middelburg', slug: 'middelburg-mpumalanga', name: 'Middelburg' },
      { name: 'Ermelo', slug: 'ermelo' },
      { name: 'Barberton', slug: 'barberton' },
      { name: 'White River', slug: 'white-river' },
      { name: 'Hazyview', slug: 'hazyview' },
      { name: 'Sabie', slug: 'sabie' },
      { name: 'Graskop', slug: 'graskop' },
      { name: 'Lydenburg', slug: 'lydenburg', alt: ['Mashishing'] },
      { name: 'Mashishing', slug: 'mashishing' },
      { name: 'Carolina', slug: 'carolina' },
      { name: 'Belfast', slug: 'belfast-mpumalanga', name: 'Belfast' },
      { name: 'Chrissiesmeer', slug: 'chrissiesmeer' },
      { name: 'Trichardt', slug: 'trichardt' },
      { name: 'Piet Retief', slug: 'piet-retief' },
      { name: 'Volksrust', slug: 'volksrust' },
      { name: 'Amersfoort', slug: 'amersfoort' },
      { name: 'Lothair', slug: 'lothair' },
    ]
  },
  {
    name: 'North West',
    slug: 'north-west',
    abbr: 'NW',
    cities: [
      { name: 'Klerksdorp', slug: 'klerksdorp' },
      { name: 'Mafikeng', slug: 'mafikeng', alt: ['Mahikeng'] },
      { name: 'Mahikeng', slug: 'mahikeng' },
      { name: 'Rustenburg', slug: 'rustenburg' },
      { name: 'Brits', slug: 'brits' },
      { name: 'Hartbeespoort', slug: 'hartbeespoort' },
      { name: 'Potchefstroom', slug: 'potchefstroom' },
      { name: 'Vryburg', slug: 'vryburg' },
      { name: 'Lichtenburg', slug: 'lichtenburg' },
      { name: 'Wolmaransstad', slug: 'wolmaransstad' },
      { name: 'Schweizer-Reneke', slug: 'schweizer-reneke' },
      { name: 'Stilfontein', slug: 'stilfontein' },
      { name: 'Orkney', slug: 'orkney' },
      { name: 'Fochville', slug: 'fochville' },
      { name: 'Coligny', slug: 'coligny' },
      { name: 'Delareyville', slug: 'delareyville' },
      { name: 'Zeerust', slug: 'zeerust' },
      { name: 'Swartruggens', slug: 'swartruggens' },
      { name: 'Koster', slug: 'koster' },
      { name: 'Groot Marico', slug: 'groot-marico' },
      { name: 'Mmabatho', slug: 'mmabatho' },
    ]
  },
  {
    name: 'Northern Cape',
    slug: 'northern-cape',
    abbr: 'NC',
    cities: [
      { name: 'Kimberley', slug: 'kimberley' },
      { name: 'Upington', slug: 'upington' },
      { name: 'Springbok', slug: 'springbok' },
      { name: 'De Aar', slug: 'de-aar' },
      { name: 'Kathu', slug: 'kathu' },
      { name: 'Kuruman', slug: 'kuruman' },
      { name: 'Prieska', slug: 'prieska' },
      { name: 'Britstown', slug: 'britstown' },
      { name: 'Carnarvon', slug: 'carnarvon' },
      { name: 'Calvinia', slug: 'calvinia' },
      { name: 'Vanrhynsdorp', slug: 'vanrhynsdorp' },
      { name: 'Vredendal', slug: 'vredendal' },
      { name: 'Clanwilliam', slug: 'clanwilliam' },
      { name: 'Sutherland', slug: 'sutherland' },
      { name: 'Victoria West', slug: 'victoria-west' },
      { name: 'Hanover', slug: 'hanover-nc', name: 'Hanover' },
      { name: 'Richmond', slug: 'richmond-nc', name: 'Richmond' },
      { name: 'Loxton', slug: 'loxton' },
      { name: 'Fraserburg', slug: 'fraserburg' },
      { name: 'Williston', slug: 'williston' },
      { name: 'Griquatown', slug: 'griquatown' },
      { name: 'Hartswater', slug: 'hartswater' },
      { name: 'Jan Kempdorp', slug: 'jan-kempdorp' },
    ]
  }
];

export const locationMap = (() => {
  const map = {};
  for (const province of saProvinces) {
    for (const city of province.cities) {
      map[city.slug] = { ...city, province: province.name, provinceSlug: province.slug };
    }
  }
  return map;
})();

export const allCitySlugs = Object.keys(locationMap);

export const allLocationKeywords = (() => {
  const keywords = new Set();
  keywords.add('south africa');
  keywords.add('sa');
  keywords.add('za');
  for (const province of saProvinces) {
    keywords.add(province.name.toLowerCase());
    keywords.add(province.abbr.toLowerCase());
    keywords.add(province.slug.replace(/-/g, ' '));
    for (const city of province.cities) {
      keywords.add(city.name.toLowerCase());
      keywords.add(city.slug.replace(/-/g, ' '));
      if (city.alt) city.alt.forEach(a => keywords.add(a.toLowerCase()));
    }
  }
  return Array.from(keywords);
})();
