import { allLocationKeywords } from './saLocations';

export const seoLocations = [
  ...allLocationKeywords,
  'south africa',
  'sa',
  'za',
  'republic of south africa',
  'rsa',
  'western cape',
  'eastern cape',
  'kwazulu-natal',
  'gauteng',
  'free state',
  'limpopo',
  'mpumalanga',
  'north west',
  'northern cape',
  'cape town',
  'johannesburg',
  'durban',
  'pretoria',
  'port elizabeth',
  'gqeberha',
  'east london',
  'bloemfontein',
  'nelspruit',
  'mbombela',
  'polokwane',
  'kimberley',
  'upington',
  'george',
  'knysna',
  'paarl',
  'stellenbosch',
  'bellville',
  'somerset west',
  'hermanus',
  'sandton',
  'midrand',
  'centurion',
  'randburg',
  'roodepoort',
  'germiston',
  'boksburg',
  'benoni',
  'vereeniging',
  'vanderbijlpark',
  'kempton park',
  'tembisa',
  'fourways',
  'bryanston',
  'pietermaritzburg',
  'umhlanga',
  'pinetown',
  'westville',
  'hillcrest',
  'amanzimtoti',
  'ballito',
  'port shepstone',
  'ladysmith',
  'newcastle',
  'richards bay',
  'witbank',
  'emalahleni',
  'secunda',
  'klerksdorp',
  'rustenburg',
  'potchefstroom',
  'brits',
  'hartbeespoort',
  'tzaneen',
  'phalaborwa',
  'thohoyandou',
  'welkom',
  'bethlehem',
  'sasolburg',
  'kroonstad',
];
