kind = "web"
previewPath = "/"
title = "Website365"
version = "1.0.0"
id = "artifacts/website365"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22642

[services.development]
run = "pnpm --filter @workspace/website365 run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/website365", "run", "build" ]
publicDir = "artifacts/website365/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22642"
BASE_PATH = "/"
