export const seoLocations = [
  'south africa',
  'sa',
  'za',
  'western cape',
  'western cape province',
  'wc',
  'western-cape',
  'eastern cape',
  'eastern cape province',
  'ec',
  'eastern-cape',
  'kwa-zulu natal',
  'kwazulu natal',
  'kwazulu-natal',
  'kzn',
  'kwa zulu natal',
  'kzn province',
  'gauteng',
  'gauteng province',
  'gp',
  'gauteng gp',
  'free state',
  'free state province',
  'fs',
  'freestate',
  'mpumalanga',
  'mpumalanga province',
  'mp',
  'northern cape',
  'northern cape province',
  'nc',
  'northern-cape',
  'north west',
  'north west province',
  'nw',
  'north-west',
  'limpopo',
  'limpopo province',
  'lp',
  'cape town',
  'capetown',
  'cape town cbd',
  'ct',
  'bellville',
  'bellville cape town',
  'paarl',
  'stellenbosch',
  'somerset west',
  'somersetwest',
  'vredendal',
  'hout bay',
  'houtbay',
  'green point',
  'greenpoint',
  'bloubergstrand',
  'blouberg',
  'durbanville',
  'melkbosstrand',
  'melkbos',
  'port elizabeth',
  'port-elizabeth',
  'gqeberha',
  'pe',
  'port elizabeth eastern cape',
  'gqeberha eastern cape',
  'knysna',
  'knysna western cape',
  'east london',
  'east london eastern cape',
  'george',
  'george western cape',
  'durban',
  'dbn',
  'pinetown',
  'ladysmith',
  'newcastle',
  'ballito',
  'port shepstone',
  'pietermaritzburg',
  'pm b',
  'umhlanga',
  'westville',
  'hillcrest',
  'amanzimtoti',
  'johannesburg',
  'joburg',
  'jozi',
  'jhb',
  'johannesburg gauteng',
  'vereeniging',
  'vaal',
  'sandton',
  'sandton johannesburg',
  'midrand',
  'pretoria',
  'pta',
  'tshwane',
  'pretoria tshwane',
  'centurion',
  'randburg',
  'roodepoort',
  'germiston',
  'alberton',
  'edenvale',
  'menlo park',
  'menlo park pretoria',
  'bloemfontein',
  'bloem',
  'welkom',
  'bethlehem',
  'bethlehem free state',
  'witbank',
  'emalahleni',
  'nelspruit',
  'mbombela',
  'de aar',
  'kimberley',
  'kimberley northern cape',
  'repra',
  'upington area',
  'upington',
  'upington northern cape',
  'klerksdorp',
  'mafikeng',
  'mahikeng',
  'mahikeng north west',
  'phalaborwa',
  'polokwane',
  'pietersburg',
  'vereeniging/vaal',
  'polokwane/pietersburg'
];
